### ISSUE TITLE
Bug in `AffineFunction` with matrix `A` going out of scope

### ISSUE THREAD

**Issue by michael-c-brennan** [MeasureTransport/MParT#275]
I have the following script for creating a ComposedMap out of many SingleEntryMaps, where each SingleEntryMap uses a SummarizedMap component:
```
maps = []

# first components don't need summaries
for idx in range(0,lrc_rank+1):
	mset = mt.MultiIndexSet.CreateTotalOrder(idx+1, total_order, noneLim)
	component = mt.CreateComponent(mset.fix(True)  , map_options)
	maps.append(mt.CreateSingleEntryMap(dim, idx+1, component))


summary_matrices = []
for idx in range(lrc_rank+1, dim):

	# create summary_matrix
	A = np.random.randn(idx, idx)
	Q, _ = np.linalg.qr(A)
	summary_matrix = Q[:lrc_rank,:].copy()

	summary_matrices.append(summary_matrix) # if you uncomment this, things work for lrc_rank = 1
	summary_fun = mt.AffineFunction(np.asfortranarray(summary_matrix))
	mset = mt.MultiIndexSet.CreateTotalOrder(lrc_rank+1, total_order, noneLim)
	component = mt.CreateComponent(mset.fix(True), map_options)
	summarized_component = mt.SummarizedMap(summary_fun, component)
	single_entry_map = mt.CreateSingleEntryMap(dim, idx+1, summarized_component)
	maps.append(single_entry_map)

transport_map = mt.ComposedMap(maps, dim)
coeffs = np.random.rand(transport_map.numCoeffs)
coeffs = coeffs/(np.linalg.norm(coeffs))
transport_map.SetCoeffs(coeffs)
```
Here `lrc_rank = 1 or 2`, small enough that each map component is cheap to evaluate. When I try to evaluate the map for a large-ish dimension (e.g. 100), I would get an error: `ERROR: In MonotoneIntegrand, A nan was encountered in value of g(df(...))`. Today @dannys4, @rubiop and I found that the values held inside `A_` of the AffineFunction object held nonsense values (with scales like 1E-160 or 1E30) using gdb. This caused the summary computed by SummarizedMap to be nonsense, and lead to the nonsense evaluation. We think this is because the variable `summary_matrix` used to create each AffineFunction gets collected by the python garbage collector after creating the AffineFunction (although disabling automatic garbage collection using `gc.disable()` doesn't help). We tried to hack it so that each `summary_matrix` would stay in scope by storing them in `summary_matrices`, which worked for `lrc_rank = 1` but it still breaks for `lrc_rank = 2` (I have no idea why). I'm looking for ideas for how to fix this.

**Comment by dannys4** [comment]
This I think should be fixed if we make a deep copy of the matrix `A` and shift `b` in the constructor for `AffineFunction` (and `AffineMap`) to store, or at least create an option to make a deep copy.

**Comment by michael-c-brennan** [comment]
Update: I added a deep_copy in AffineFunction
```
template<typename MemorySpace>
AffineFunction<MemorySpace>::AffineFunction(StridedMatrix<double,MemorySpace> A) : ParameterizedFunctionBase<MemorySpace>(A.extent(1),A.extent(0),0),
                                                                                   A_(A)
{
    Kokkos::deep_copy(A_, A);
    assert(A_.extent(0)<=A_.extent(1));
}
```
but this doesn't seem to solve it. I added a function to AffineFunction that prints `A_(i,j)` for inputs `i,j` to help debug. Running the following, the value of A_(0,0) for the first AffineFunction created changes while the loop is running
```
# lists to hold summary_matrices and functions
summary_matrices = []
summary_funs = []
for idx in range(lrc_rank+1, dim):

	# create summary_matrix
	A = np.random.randn(idx, idx)
	Q, _ = np.linalg.qr(A)
	summary_matrix = Q[:lrc_rank,:].copy()
	summary_matrices.append(summary_matrix)  

	# create summary function
	summary_fun = mt.AffineFunction(np.asfortranarray(summary_matrix))
	summary_funs.append(summary_fun)

	# print first entry of the first summary_matrix and the A_ variable held by summary_funs
	print("idx={}".format(idx))
	print("python: summary_matrix(0,0) = {}".format(summary_matrices[0][0,0]))
	summary_funs[0].print_Aij(0,0)
```
Output (the change happens at idx = 6)
```
Kokkos is using 1 threads
num_maps: 10
idx=3
python: summary_matrix(0,0) = -0.41606386671429174
A(0,0) = -0.416064
idx=4
python: summary_matrix(0,0) = -0.41606386671429174
A(0,0) = -0.416064
idx=5
python: summary_matrix(0,0) = -0.41606386671429174
A(0,0) = -0.416064
idx=6
python: summary_matrix(0,0) = -0.41606386671429174
A(0,0) = 1.15913
idx=7
python: summary_matrix(0,0) = -0.41606386671429174
A(0,0) = 1.15913
idx=8
python: summary_matrix(0,0) = -0.41606386671429174
A(0,0) = 1.15913
idx=9
python: summary_matrix(0,0) = -0.41606386671429174
A(0,0) = 1.15913
```

**Comment by mparno** [comment]
Hey @michael-c-brennan !   I suspect I know what might be happening.   I think your intuition for using the `deep_copy` is correct, but there are some subtleties we need to address to get the copy to function properly.   The `summary_matrix` you're using to define the `AffineFunction` goes out of scope at the end of the for loop, so it will get cleaned up by python.  However, the `A_` view inside `AffineFunction` will still be pointing to the memory used by `summary_matrix` because we expose numpy arrays to `c++` via unmanaged Kokkos views.    

The `deep_copy` you have right now doesn't fix this because the view `A_` is constructed by just copying `A`, so the member `A_` will also be an unmanaged view wrapping around memory in the original numpy array.  The `deep_copy` doesn't set up any new memory, it just copies the contents of `A` into `A_`, so it's actually just copying the contents of the numpy memory back into itself.

To get the `deep_copy` to behave like you want, you'll have to construct `A_` differently so that it has its own memory to copy the contents of `A` into.     For example, the following might work (uncompiled/tested):
```c++
template<typename MemorySpace>
AffineFunction<MemorySpace>::AffineFunction(StridedMatrix<double,MemorySpace> A) : ParameterizedFunctionBase<MemorySpace>(A.extent(1),A.extent(0),0),
                                                                               A_("A", A.extent(0), A.extent(1))
{
    Kokkos::deep_copy(A_, A);
    assert(A_.extent(0)<=A_.extent(1));
}
```

**Comment by michael-c-brennan** [comment]
Hey @mparno! Your explanation helped a lot, thank you! Your example solved it after changing `A_("A", A.extent(0), A.extent(1))` to `A_("A", A.layout())`. Working on a PR for this fix in `AffineMap` and `AffineFunction` now.
